### ISSUE TITLE
When will the complete code be uploaded?

### ISSUE THREAD

**Issue by Quinntt** [sukun1045/video-physics-sound-diffusion#1]
Hi Sukun, 
thanks for the great project.
May I ask whether the code is not complete at present?  When I tried to extract the residual parameters, I only found the sound_residual_train.py in the tools folder, and there seems to be no prediction of residual parameters. As well as the related files of video_root, video_fea_root and latent_root mentioned in GreatHitsDiffDataset, the corresponding feature extraction code was not found.  May I ask when the complete code will be uploaded to github? 
Thank you.

**Comment by sukun1045** [comment]
Hi, thanks for your interest. Sorry I am overwhelmed by some other important items, but I will update the repo soon (with all things you mentioned). Probably in about 2-3 weeks. Thank you.
