### ISSUE TITLE
Does the training loss of Sound_residual_predict  only have one kind of Mrft_loss?

### ISSUE THREAD

**Issue by SuperiorDtj** [sukun1045/video-physics-sound-diffusion#4]
When I try to train sound_phsics_residual_predict , there is erro:
  The SoundResidualCriterion need four paras(gt/predict audio and gt/predict fea), but the trainer only pass it gt/predict audio to calculate Mrft_loss. 
  Is the percept loss needing gt/predict fea necessary?

**Comment by sukun1045** [comment]
Thanks for pointing it out. It was redundant code that I forgot to clean. I tried adding perceptual loss before but I remembered it didn't help. So feel free to delete it

**Comment by SuperiorDtj** [comment]
> Thanks for pointing it out. It was redundant code that I forgot to clean. I tried adding perceptual loss before but I remembered it didn't help. So feel free to delete it

Thanks for your quick replying!

I have another questions:
   When extrating phsics paras,  there are two number I cannot understand. One is frequency distance **10.76**, and another is **60** / final_d.
   Is there any reference material to explain these specific numbers？
<img width="544" alt="屏幕截图 2024-03-01 124634" src="https://github.com/sukun1045/video-physics-sound-diffusion/assets/90552070/0b7437bf-fe2f-45b4-8c7e-b5dd1bdb6752">

**Comment by sukun1045** [comment]
Sorry for the confusion, the first number is a hard-code for 44100/2048/2, giving a rough range of the frequency range within one bin. The second one refers to '60dB'. You can check out the code in [TDW](https://github.com/threedworld-mit/tdw/blob/f836fe4e567dc397217125a6e32437a75588475c/Python/tdw/physics_audio/modes.py#L56) repo.

**Comment by SuperiorDtj** [comment]
> Sorry for the confusion, the first number is a hard-code for 44100/2048/2, giving a rough range of the frequency range within one bin. The second one refers to '60dB'. You can check out the code in [TDW](https://github.com/threedworld-mit/tdw/blob/f836fe4e567dc397217125a6e32437a75588475c/Python/tdw/physics_audio/modes.py#L56) repo.

Thank you for your prompt and detailed reply!!
