### ISSUE TITLE
data missed

### ISSUE THREAD

**Issue by SuperiorDtj** [sukun1045/video-physics-sound-diffusion#5]
`GreatHitsDiffDatasets `specifies `audio_root `as `hits_100_mode_data_ten`, but only `hits_mode_data_ten `is availiable in google drive or can be obtained by python scripts in code.  Are they same data?
Familiarly，`latent_path `is specified as `hits_mode_data_ten_phsics_noise_paras`, but only `hits_mode_data_ten_phsics_residual_paras `is availiable.

**Comment by sukun1045** [comment]
Hi, they are the same thing. Just want to make a better name to clarify what they are

**Comment by SuperiorDtj** [comment]
Thank you very much!
